/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../../../common.js"
  
export declare namespace InterfoldToken {
      
    export type CurveStruct = {anchor: BigNumberish, start: BigNumberish, cliffDuration: BigNumberish, vestDuration: BigNumberish}

    export type CurveStructOutput = [anchor: bigint, start: bigint, cliffDuration: bigint, vestDuration: bigint] & {anchor: bigint, start: bigint, cliffDuration: bigint, vestDuration: bigint }
  

    export type LockPolicyStruct = {holdUntil: BigNumberish, unlock: InterfoldToken.CurveStruct}

    export type LockPolicyStructOutput = [holdUntil: bigint, unlock: InterfoldToken.CurveStructOutput] & {holdUntil: bigint, unlock: InterfoldToken.CurveStructOutput }
  

    export type MintAllocationStruct = {recipient: AddressLike, amount: BigNumberish, policyId: BytesLike, label: BytesLike}

    export type MintAllocationStructOutput = [recipient: string, amount: bigint, policyId: string, label: string] & {recipient: string, amount: bigint, policyId: string, label: string }
  
    }

export declare namespace Checkpoints {
      
    export type Checkpoint208Struct = {_key: BigNumberish, _value: BigNumberish}

    export type Checkpoint208StructOutput = [_key: bigint, _value: bigint] & {_key: bigint, _value: bigint }
  
    }

  export interface InterfoldTokenInterface extends Interface {
    getFunction(nameOrSignature: "BONDING_REGISTRY" | "CCA_END" | "CCA_START" | "CLAIM_SOURCE" | "CLOCK_MODE" | "DEFAULT_ADMIN_ROLE" | "DOMAIN_SEPARATOR" | "LOCK_MANAGER_ROLE" | "MAX_LOCKS_PER_ACCOUNT" | "MAX_QUEUED_LOCKS_PER_ACCOUNT" | "MAX_SUPPLY" | "MINTER_ROLE" | "NO_MORE_LOCKS" | "PENDING_LOCK_POLICY_ID" | "TGE_COOLDOWN" | "WHITELIST_ROLE" | "acceptOwnership" | "allowance" | "approve" | "balanceOf" | "checkpoints" | "claimLockExempt" | "clock" | "createLockPolicy" | "decimals" | "delegate" | "delegateBySig" | "delegates" | "eip712Domain" | "getPastTotalSupply" | "getPastVotes" | "getRoleAdmin" | "getVotes" | "grantRole" | "hasRole" | "linkClaim" | "lockCount" | "lockPolicyOf" | "lockedBalanceAt" | "lockedBalanceOf" | "locks" | "mint" | "mintAllocations" | "name" | "nonces" | "numCheckpoints" | "owner" | "pendingOwner" | "permit" | "phase" | "queuedLockCount" | "queuedLocks" | "relinkActiveLock" | "renounceOwnership" | "renounceRole" | "revokeRole" | "setClaimLockExempt" | "setTransferWhitelisted" | "supportsInterface" | "symbol" | "tge" | "tgeTimestamp" | "totalSupply" | "transfer" | "transferFrom" | "transferOwnership" | "transferWhitelist" | "transferableBalanceOf"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ActiveLockRelinked" | "ActiveLockUpdated" | "AllocationMinted" | "Approval" | "ClaimLockExemptUpdated" | "DelegateChanged" | "DelegateVotesChanged" | "EIP712DomainChanged" | "OwnershipTransferStarted" | "OwnershipTransferred" | "PolicyDefined" | "QueuedLockUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "TgeTriggered" | "Transfer" | "TransferWhitelistUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'BONDING_REGISTRY', values?: undefined): string;
encodeFunctionData(functionFragment: 'CCA_END', values?: undefined): string;
encodeFunctionData(functionFragment: 'CCA_START', values?: undefined): string;
encodeFunctionData(functionFragment: 'CLAIM_SOURCE', values?: undefined): string;
encodeFunctionData(functionFragment: 'CLOCK_MODE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DOMAIN_SEPARATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'LOCK_MANAGER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_LOCKS_PER_ACCOUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_QUEUED_LOCKS_PER_ACCOUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SUPPLY', values?: undefined): string;
encodeFunctionData(functionFragment: 'MINTER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'NO_MORE_LOCKS', values?: undefined): string;
encodeFunctionData(functionFragment: 'PENDING_LOCK_POLICY_ID', values?: undefined): string;
encodeFunctionData(functionFragment: 'TGE_COOLDOWN', values?: undefined): string;
encodeFunctionData(functionFragment: 'WHITELIST_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'checkpoints', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimLockExempt', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'clock', values?: undefined): string;
encodeFunctionData(functionFragment: 'createLockPolicy', values: [BytesLike, InterfoldToken.LockPolicyStruct]): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'delegate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'delegateBySig', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'delegates', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'eip712Domain', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPastTotalSupply', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPastVotes', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getVotes', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'linkClaim', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'lockCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lockPolicyOf', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'lockedBalanceAt', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockedBalanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'locks', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'mintAllocations', values: [InterfoldToken.MintAllocationStruct[]]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'nonces', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'numCheckpoints', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'permit', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'phase', values?: undefined): string;
encodeFunctionData(functionFragment: 'queuedLockCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'queuedLocks', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'relinkActiveLock', values: [AddressLike, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setClaimLockExempt', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setTransferWhitelisted', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tge', values?: undefined): string;
encodeFunctionData(functionFragment: 'tgeTimestamp', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferWhitelist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferableBalanceOf', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'BONDING_REGISTRY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CCA_END', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CCA_START', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CLAIM_SOURCE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CLOCK_MODE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DOMAIN_SEPARATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LOCK_MANAGER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_LOCKS_PER_ACCOUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_QUEUED_LOCKS_PER_ACCOUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SUPPLY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MINTER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'NO_MORE_LOCKS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PENDING_LOCK_POLICY_ID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TGE_COOLDOWN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WHITELIST_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkpoints', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimLockExempt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'clock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createLockPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'delegate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'delegateBySig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'delegates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eip712Domain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPastTotalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPastVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'linkClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockPolicyOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedBalanceAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedBalanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'locks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintAllocations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'numCheckpoints', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'permit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'phase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'queuedLockCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'queuedLocks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'relinkActiveLock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setClaimLockExempt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTransferWhitelisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tgeTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferableBalanceOf', data: BytesLike): Result;
  }

  
    export namespace ActiveLockRelinkedEvent {
      export type InputTuple = [account: AddressLike, fromPolicyId: BytesLike, toPolicyId: BytesLike, amount: BigNumberish];
      export type OutputTuple = [account: string, fromPolicyId: string, toPolicyId: string, amount: bigint];
      export interface OutputObject {account: string, fromPolicyId: string, toPolicyId: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ActiveLockUpdatedEvent {
      export type InputTuple = [account: AddressLike, policyId: BytesLike, amount: BigNumberish];
      export type OutputTuple = [account: string, policyId: string, amount: bigint];
      export interface OutputObject {account: string, policyId: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AllocationMintedEvent {
      export type InputTuple = [recipient: AddressLike, amount: BigNumberish, policyId: BytesLike, label: BytesLike];
      export type OutputTuple = [recipient: string, amount: bigint, policyId: string, label: string];
      export interface OutputObject {recipient: string, amount: bigint, policyId: string, label: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimLockExemptUpdatedEvent {
      export type InputTuple = [account: AddressLike, exempt: boolean];
      export type OutputTuple = [account: string, exempt: boolean];
      export interface OutputObject {account: string, exempt: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DelegateChangedEvent {
      export type InputTuple = [delegator: AddressLike, fromDelegate: AddressLike, toDelegate: AddressLike];
      export type OutputTuple = [delegator: string, fromDelegate: string, toDelegate: string];
      export interface OutputObject {delegator: string, fromDelegate: string, toDelegate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DelegateVotesChangedEvent {
      export type InputTuple = [delegate: AddressLike, previousVotes: BigNumberish, newVotes: BigNumberish];
      export type OutputTuple = [delegate: string, previousVotes: bigint, newVotes: bigint];
      export interface OutputObject {delegate: string, previousVotes: bigint, newVotes: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EIP712DomainChangedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyDefinedEvent {
      export type InputTuple = [policyId: BytesLike, policy: InterfoldToken.LockPolicyStruct];
      export type OutputTuple = [policyId: string, policy: InterfoldToken.LockPolicyStructOutput];
      export interface OutputObject {policyId: string, policy: InterfoldToken.LockPolicyStructOutput };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace QueuedLockUpdatedEvent {
      export type InputTuple = [account: AddressLike, policyId: BytesLike, amount: BigNumberish];
      export type OutputTuple = [account: string, policyId: string, amount: bigint];
      export interface OutputObject {account: string, policyId: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TgeTriggeredEvent {
      export type InputTuple = [timestamp: BigNumberish];
      export type OutputTuple = [timestamp: bigint];
      export interface OutputObject {timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferWhitelistUpdatedEvent {
      export type InputTuple = [account: AddressLike, whitelisted: boolean];
      export type OutputTuple = [account: string, whitelisted: boolean];
      export interface OutputObject {account: string, whitelisted: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface InterfoldToken extends BaseContract {
    
    connect(runner?: ContractRunner | null): InterfoldToken;
    waitForDeployment(): Promise<this>;

    interface: InterfoldTokenInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BONDING_REGISTRY: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    CCA_END: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    CCA_START: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    CLAIM_SOURCE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    CLOCK_MODE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DOMAIN_SEPARATOR: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    LOCK_MANAGER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MAX_LOCKS_PER_ACCOUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_QUEUED_LOCKS_PER_ACCOUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_SUPPLY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MINTER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    NO_MORE_LOCKS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PENDING_LOCK_POLICY_ID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    TGE_COOLDOWN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    WHITELIST_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    checkpoints: TypedContractMethod<
      [account: AddressLike, pos: BigNumberish, ],
      [Checkpoints.Checkpoint208StructOutput],
      'view'
    >
    

    
    claimLockExempt: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    clock: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createLockPolicy: TypedContractMethod<
      [policyId: BytesLike, policy: InterfoldToken.LockPolicyStruct, ],
      [void],
      'nonpayable'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    delegate: TypedContractMethod<
      [delegatee: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    delegateBySig: TypedContractMethod<
      [delegatee: AddressLike, nonce: BigNumberish, expiry: BigNumberish, v: BigNumberish, r: BytesLike, s: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    delegates: TypedContractMethod<
      [account: AddressLike, ],
      [string],
      'view'
    >
    

    
    eip712Domain: TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >
    

    
    getPastTotalSupply: TypedContractMethod<
      [timepoint: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getPastVotes: TypedContractMethod<
      [account: AddressLike, timepoint: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getVotes: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    linkClaim: TypedContractMethod<
      [account: AddressLike, amount: BigNumberish, policyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    lockCount: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    lockPolicyOf: TypedContractMethod<
      [policyId: BytesLike, ],
      [InterfoldToken.LockPolicyStructOutput],
      'view'
    >
    

    
    lockedBalanceAt: TypedContractMethod<
      [account: AddressLike, timestamp: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    lockedBalanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    locks: TypedContractMethod<
      [account: AddressLike, arg1: BigNumberish, ],
      [[string, bigint] & {policyId: string, amount: bigint }],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, label: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    mintAllocations: TypedContractMethod<
      [allocations: InterfoldToken.MintAllocationStruct[], ],
      [void],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    nonces: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    numCheckpoints: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    permit: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, value: BigNumberish, deadline: BigNumberish, v: BigNumberish, r: BytesLike, s: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    phase: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    queuedLockCount: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    queuedLocks: TypedContractMethod<
      [account: AddressLike, arg1: BigNumberish, ],
      [[string, bigint] & {policyId: string, amount: bigint }],
      'view'
    >
    

    
    relinkActiveLock: TypedContractMethod<
      [account: AddressLike, fromPolicyId: BytesLike, toPolicyId: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setClaimLockExempt: TypedContractMethod<
      [account: AddressLike, exempt: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setTransferWhitelisted: TypedContractMethod<
      [account: AddressLike, whitelisted: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tge: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    tgeTimestamp: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferWhitelist: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    transferableBalanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BONDING_REGISTRY'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'CCA_END'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'CCA_START'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'CLAIM_SOURCE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'CLOCK_MODE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DOMAIN_SEPARATOR'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'LOCK_MANAGER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_LOCKS_PER_ACCOUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_QUEUED_LOCKS_PER_ACCOUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SUPPLY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MINTER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'NO_MORE_LOCKS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PENDING_LOCK_POLICY_ID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'TGE_COOLDOWN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'WHITELIST_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'checkpoints'): TypedContractMethod<
      [account: AddressLike, pos: BigNumberish, ],
      [Checkpoints.Checkpoint208StructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'claimLockExempt'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'clock'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createLockPolicy'): TypedContractMethod<
      [policyId: BytesLike, policy: InterfoldToken.LockPolicyStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'delegate'): TypedContractMethod<
      [delegatee: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'delegateBySig'): TypedContractMethod<
      [delegatee: AddressLike, nonce: BigNumberish, expiry: BigNumberish, v: BigNumberish, r: BytesLike, s: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'delegates'): TypedContractMethod<
      [account: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'eip712Domain'): TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getPastTotalSupply'): TypedContractMethod<
      [timepoint: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPastVotes'): TypedContractMethod<
      [account: AddressLike, timepoint: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getVotes'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'linkClaim'): TypedContractMethod<
      [account: AddressLike, amount: BigNumberish, policyId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lockCount'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lockPolicyOf'): TypedContractMethod<
      [policyId: BytesLike, ],
      [InterfoldToken.LockPolicyStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'lockedBalanceAt'): TypedContractMethod<
      [account: AddressLike, timestamp: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lockedBalanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'locks'): TypedContractMethod<
      [account: AddressLike, arg1: BigNumberish, ],
      [[string, bigint] & {policyId: string, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, label: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintAllocations'): TypedContractMethod<
      [allocations: InterfoldToken.MintAllocationStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nonces'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'numCheckpoints'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'permit'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, value: BigNumberish, deadline: BigNumberish, v: BigNumberish, r: BytesLike, s: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'phase'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'queuedLockCount'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'queuedLocks'): TypedContractMethod<
      [account: AddressLike, arg1: BigNumberish, ],
      [[string, bigint] & {policyId: string, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'relinkActiveLock'): TypedContractMethod<
      [account: AddressLike, fromPolicyId: BytesLike, toPolicyId: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setClaimLockExempt'): TypedContractMethod<
      [account: AddressLike, exempt: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTransferWhitelisted'): TypedContractMethod<
      [account: AddressLike, whitelisted: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tge'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tgeTimestamp'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferWhitelist'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferableBalanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'ActiveLockRelinked'): TypedContractEvent<ActiveLockRelinkedEvent.InputTuple, ActiveLockRelinkedEvent.OutputTuple, ActiveLockRelinkedEvent.OutputObject>;
getEvent(key: 'ActiveLockUpdated'): TypedContractEvent<ActiveLockUpdatedEvent.InputTuple, ActiveLockUpdatedEvent.OutputTuple, ActiveLockUpdatedEvent.OutputObject>;
getEvent(key: 'AllocationMinted'): TypedContractEvent<AllocationMintedEvent.InputTuple, AllocationMintedEvent.OutputTuple, AllocationMintedEvent.OutputObject>;
getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ClaimLockExemptUpdated'): TypedContractEvent<ClaimLockExemptUpdatedEvent.InputTuple, ClaimLockExemptUpdatedEvent.OutputTuple, ClaimLockExemptUpdatedEvent.OutputObject>;
getEvent(key: 'DelegateChanged'): TypedContractEvent<DelegateChangedEvent.InputTuple, DelegateChangedEvent.OutputTuple, DelegateChangedEvent.OutputObject>;
getEvent(key: 'DelegateVotesChanged'): TypedContractEvent<DelegateVotesChangedEvent.InputTuple, DelegateVotesChangedEvent.OutputTuple, DelegateVotesChangedEvent.OutputObject>;
getEvent(key: 'EIP712DomainChanged'): TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PolicyDefined'): TypedContractEvent<PolicyDefinedEvent.InputTuple, PolicyDefinedEvent.OutputTuple, PolicyDefinedEvent.OutputObject>;
getEvent(key: 'QueuedLockUpdated'): TypedContractEvent<QueuedLockUpdatedEvent.InputTuple, QueuedLockUpdatedEvent.OutputTuple, QueuedLockUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'TgeTriggered'): TypedContractEvent<TgeTriggeredEvent.InputTuple, TgeTriggeredEvent.OutputTuple, TgeTriggeredEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'TransferWhitelistUpdated'): TypedContractEvent<TransferWhitelistUpdatedEvent.InputTuple, TransferWhitelistUpdatedEvent.OutputTuple, TransferWhitelistUpdatedEvent.OutputObject>;

    filters: {
      
      'ActiveLockRelinked(address,bytes32,bytes32,uint256)': TypedContractEvent<ActiveLockRelinkedEvent.InputTuple, ActiveLockRelinkedEvent.OutputTuple, ActiveLockRelinkedEvent.OutputObject>;
      ActiveLockRelinked: TypedContractEvent<ActiveLockRelinkedEvent.InputTuple, ActiveLockRelinkedEvent.OutputTuple, ActiveLockRelinkedEvent.OutputObject>;
    

      'ActiveLockUpdated(address,bytes32,uint256)': TypedContractEvent<ActiveLockUpdatedEvent.InputTuple, ActiveLockUpdatedEvent.OutputTuple, ActiveLockUpdatedEvent.OutputObject>;
      ActiveLockUpdated: TypedContractEvent<ActiveLockUpdatedEvent.InputTuple, ActiveLockUpdatedEvent.OutputTuple, ActiveLockUpdatedEvent.OutputObject>;
    

      'AllocationMinted(address,uint256,bytes32,bytes32)': TypedContractEvent<AllocationMintedEvent.InputTuple, AllocationMintedEvent.OutputTuple, AllocationMintedEvent.OutputObject>;
      AllocationMinted: TypedContractEvent<AllocationMintedEvent.InputTuple, AllocationMintedEvent.OutputTuple, AllocationMintedEvent.OutputObject>;
    

      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ClaimLockExemptUpdated(address,bool)': TypedContractEvent<ClaimLockExemptUpdatedEvent.InputTuple, ClaimLockExemptUpdatedEvent.OutputTuple, ClaimLockExemptUpdatedEvent.OutputObject>;
      ClaimLockExemptUpdated: TypedContractEvent<ClaimLockExemptUpdatedEvent.InputTuple, ClaimLockExemptUpdatedEvent.OutputTuple, ClaimLockExemptUpdatedEvent.OutputObject>;
    

      'DelegateChanged(address,address,address)': TypedContractEvent<DelegateChangedEvent.InputTuple, DelegateChangedEvent.OutputTuple, DelegateChangedEvent.OutputObject>;
      DelegateChanged: TypedContractEvent<DelegateChangedEvent.InputTuple, DelegateChangedEvent.OutputTuple, DelegateChangedEvent.OutputObject>;
    

      'DelegateVotesChanged(address,uint256,uint256)': TypedContractEvent<DelegateVotesChangedEvent.InputTuple, DelegateVotesChangedEvent.OutputTuple, DelegateVotesChangedEvent.OutputObject>;
      DelegateVotesChanged: TypedContractEvent<DelegateVotesChangedEvent.InputTuple, DelegateVotesChangedEvent.OutputTuple, DelegateVotesChangedEvent.OutputObject>;
    

      'EIP712DomainChanged()': TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
      EIP712DomainChanged: TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PolicyDefined(bytes32,tuple)': TypedContractEvent<PolicyDefinedEvent.InputTuple, PolicyDefinedEvent.OutputTuple, PolicyDefinedEvent.OutputObject>;
      PolicyDefined: TypedContractEvent<PolicyDefinedEvent.InputTuple, PolicyDefinedEvent.OutputTuple, PolicyDefinedEvent.OutputObject>;
    

      'QueuedLockUpdated(address,bytes32,uint256)': TypedContractEvent<QueuedLockUpdatedEvent.InputTuple, QueuedLockUpdatedEvent.OutputTuple, QueuedLockUpdatedEvent.OutputObject>;
      QueuedLockUpdated: TypedContractEvent<QueuedLockUpdatedEvent.InputTuple, QueuedLockUpdatedEvent.OutputTuple, QueuedLockUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'TgeTriggered(uint64)': TypedContractEvent<TgeTriggeredEvent.InputTuple, TgeTriggeredEvent.OutputTuple, TgeTriggeredEvent.OutputObject>;
      TgeTriggered: TypedContractEvent<TgeTriggeredEvent.InputTuple, TgeTriggeredEvent.OutputTuple, TgeTriggeredEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'TransferWhitelistUpdated(address,bool)': TypedContractEvent<TransferWhitelistUpdatedEvent.InputTuple, TransferWhitelistUpdatedEvent.OutputTuple, TransferWhitelistUpdatedEvent.OutputObject>;
      TransferWhitelistUpdated: TypedContractEvent<TransferWhitelistUpdatedEvent.InputTuple, TransferWhitelistUpdatedEvent.OutputTuple, TransferWhitelistUpdatedEvent.OutputObject>;
    
    };
  }