/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../../common.js"
  import type { MockPkVerifier, MockPkVerifierInterface } from "../../../../../@interfold/contracts/contracts/test/MockPkVerifier.js";

  const _abi = [
  {
    "inputs": [],
    "name": "DomainBindingMismatch",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidProof",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidPublicInputsLength",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PkCommitmentMismatch",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VkHashMismatch",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      },
      {
        "internalType": "bytes32",
        "name": "pkCommitment",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "proof",
        "type": "bytes"
      }
    ],
    "name": "verify",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506103a88061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c80630741a9da1461002d575b5f5ffd5b61004061003b366004610120565b610054565b604051901515815260200160405180910390f35b5f80610062838501856102a6565b91505080515f0361008657604051633e15742360e01b815260040160405180910390fd5b8581600183516100969190610362565b815181106100a6576100a6610387565b6020026020010151146100cc5760405163151637bd60e31b815260040160405180910390fd5b5060019998505050505050505050565b5f5f83601f8401126100ec575f5ffd5b5081356001600160401b03811115610102575f5ffd5b602083019150836020828501011115610119575f5ffd5b9250929050565b5f5f5f5f5f5f5f5f60c0898b031215610137575f5ffd5b883597506020890135965060408901356001600160401b0381111561015a575f5ffd5b8901601f81018b1361016a575f5ffd5b80356001600160401b0381111561017f575f5ffd5b8b60208260051b8401011115610193575f5ffd5b60209190910196509450606089013593506080890135925060a08901356001600160401b038111156101c3575f5ffd5b6101cf8b828c016100dc565b999c989b5096995094979396929594505050565b634e487b7160e01b5f52604160045260245ffd5b604051601f8201601f191681016001600160401b038111828210171561021f5761021f6101e3565b604052919050565b5f82601f830112610236575f5ffd5b81356001600160401b0381111561024f5761024f6101e3565b8060051b61025f602082016101f7565b9182526020818501810192908101908684111561027a575f5ffd5b6020860192505b8383101561029c578235825260209283019290910190610281565b9695505050505050565b5f5f604083850312156102b7575f5ffd5b82356001600160401b038111156102cc575f5ffd5b8301601f810185136102dc575f5ffd5b80356001600160401b038111156102f5576102f56101e3565b610308601f8201601f19166020016101f7565b81815286602083850101111561031c575f5ffd5b816020840160208301375f6020838301015280945050505060208301356001600160401b0381111561034c575f5ffd5b61035885828601610227565b9150509250929050565b8181038181111561038157634e487b7160e01b5f52601160045260245ffd5b92915050565b634e487b7160e01b5f52603260045260245ffdfea164736f6c634300081c000a";

  
      type MockPkVerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockPkVerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockPkVerifier__factory extends ContractFactory {
    
      constructor(...args: MockPkVerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockPkVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockPkVerifier__factory {
      return super.connect(runner) as MockPkVerifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockPkVerifierInterface {
      return new Interface(_abi) as MockPkVerifierInterface;
    }
    
    override attach(address: string | Addressable): MockPkVerifier {
      return super.attach(address) as MockPkVerifier;
    }
  static connect(address: string, runner?: ContractRunner | null): MockPkVerifier {
      return new Contract(address, _abi, runner) as unknown as MockPkVerifier;
    }
  }

  
  