/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as decryptionAggregatorVerifierSol from './DecryptionAggregatorVerifier.sol/index.js';
export type { decryptionAggregatorVerifierSol };
import type * as dkgAggregatorVerifierSol from './DkgAggregatorVerifier.sol/index.js';
export type { dkgAggregatorVerifierSol };