/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../../../../common.js"
  

  export interface BfvPkVerifierInterface extends Interface {
    getFunction(nameOrSignature: "circuitVerifier" | "expectedC5KeyHash" | "expectedNodesFoldKeyHash" | "h" | "verify"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'circuitVerifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'expectedC5KeyHash', values?: undefined): string;
encodeFunctionData(functionFragment: 'expectedNodesFoldKeyHash', values?: undefined): string;
encodeFunctionData(functionFragment: 'h', values?: undefined): string;
encodeFunctionData(functionFragment: 'verify', values: [BigNumberish, BigNumberish, AddressLike[], BytesLike, BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'circuitVerifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'expectedC5KeyHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'expectedNodesFoldKeyHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'h', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
  }

  

  export interface BfvPkVerifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): BfvPkVerifier;
    waitForDeployment(): Promise<this>;

    interface: BfvPkVerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    circuitVerifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    expectedC5KeyHash: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    expectedNodesFoldKeyHash: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    h: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    verify: TypedContractMethod<
      [e3Id: BigNumberish, committeeRoot: BigNumberish, sortedNodes: AddressLike[], pkCommitment: BytesLike, committeeHash: BytesLike, proof: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'circuitVerifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'expectedC5KeyHash'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'expectedNodesFoldKeyHash'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'h'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [e3Id: BigNumberish, committeeRoot: BigNumberish, sortedNodes: AddressLike[], pkCommitment: BytesLike, committeeHash: BytesLike, proof: BytesLike, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }