/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MyProgramInterface extends Interface {
    getFunction(nameOrSignature: "ENCRYPTION_SCHEME_ID" | "TREE_DEPTH" | "authorizedContracts" | "imageId" | "inputs" | "interfold" | "owner" | "paramsHashes" | "publishInput" | "renounceOwnership" | "transferOwnership" | "validate" | "verifier" | "verify"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "InputPublished" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'ENCRYPTION_SCHEME_ID', values?: undefined): string;
encodeFunctionData(functionFragment: 'TREE_DEPTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'authorizedContracts', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'imageId', values?: undefined): string;
encodeFunctionData(functionFragment: 'inputs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'interfold', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paramsHashes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'publishInput', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'validate', values: [BigNumberish, BigNumberish, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'verifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'verify', values: [BigNumberish, BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'ENCRYPTION_SCHEME_ID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TREE_DEPTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedContracts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'imageId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inputs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'interfold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paramsHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishInput', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
  }

  
    export namespace InputPublishedEvent {
      export type InputTuple = [e3Id: BigNumberish, data: BytesLike, index: BigNumberish];
      export type OutputTuple = [e3Id: bigint, data: string, index: bigint];
      export interface OutputObject {e3Id: bigint, data: string, index: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MyProgram extends BaseContract {
    
    connect(runner?: ContractRunner | null): MyProgram;
    waitForDeployment(): Promise<this>;

    interface: MyProgramInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ENCRYPTION_SCHEME_ID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    TREE_DEPTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    authorizedContracts: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    imageId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    inputs: TypedContractMethod<
      [e3Id: BigNumberish, ],
      [[bigint, bigint] & {maxIndex: bigint, numberOfLeaves: bigint }],
      'view'
    >
    

    
    interfold: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paramsHashes: TypedContractMethod<
      [e3Id: BigNumberish, ],
      [string],
      'view'
    >
    

    
    publishInput: TypedContractMethod<
      [e3Id: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    validate: TypedContractMethod<
      [e3Id: BigNumberish, arg1: BigNumberish, e3ProgramParams: BytesLike, arg3: BytesLike, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verify: TypedContractMethod<
      [e3Id: BigNumberish, ciphertextOutputHash: BytesLike, proof: BytesLike, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ENCRYPTION_SCHEME_ID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'TREE_DEPTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'authorizedContracts'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'imageId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'inputs'): TypedContractMethod<
      [e3Id: BigNumberish, ],
      [[bigint, bigint] & {maxIndex: bigint, numberOfLeaves: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'interfold'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paramsHashes'): TypedContractMethod<
      [e3Id: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'publishInput'): TypedContractMethod<
      [e3Id: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'validate'): TypedContractMethod<
      [e3Id: BigNumberish, arg1: BigNumberish, e3ProgramParams: BytesLike, arg3: BytesLike, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [e3Id: BigNumberish, ciphertextOutputHash: BytesLike, proof: BytesLike, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'InputPublished'): TypedContractEvent<InputPublishedEvent.InputTuple, InputPublishedEvent.OutputTuple, InputPublishedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'InputPublished(uint256,bytes,uint256)': TypedContractEvent<InputPublishedEvent.InputTuple, InputPublishedEvent.OutputTuple, InputPublishedEvent.OutputObject>;
      InputPublished: TypedContractEvent<InputPublishedEvent.InputTuple, InputPublishedEvent.OutputTuple, InputPublishedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }