/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../../../../common.js"
  import type { MockCircuitVerifier, MockCircuitVerifierInterface } from "../../../../../../@interfold/contracts/contracts/test/MockSlashingVerifier.sol/MockCircuitVerifier.js";

  const _abi = [
  {
    "inputs": [],
    "name": "returnValue",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "_returnValue",
        "type": "bool"
      }
    ],
    "name": "setReturnValue",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      },
      {
        "internalType": "bytes32[]",
        "name": "",
        "type": "bytes32[]"
      }
    ],
    "name": "verify",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5061019b8061001c5f395ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c8063990c8f7914610043578063d2c6417614610063578063ea50d0e414610085575b5f5ffd5b5f5461004f9060ff1681565b604051901515815260200160405180910390f35b6100836100713660046100a0565b5f805460ff1916911515919091179055565b005b61004f6100933660046100c6565b5f5460ff16949350505050565b5f602082840312156100b0575f5ffd5b813580151581146100bf575f5ffd5b9392505050565b5f5f5f5f604085870312156100d9575f5ffd5b843567ffffffffffffffff8111156100ef575f5ffd5b8501601f810187136100ff575f5ffd5b803567ffffffffffffffff811115610115575f5ffd5b876020828401011115610126575f5ffd5b60209182019550935085013567ffffffffffffffff811115610146575f5ffd5b8501601f81018713610156575f5ffd5b803567ffffffffffffffff81111561016c575f5ffd5b8760208260051b8401011115610180575f5ffd5b94979396506020019450505056fea164736f6c634300081c000a";

  
      type MockCircuitVerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockCircuitVerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockCircuitVerifier__factory extends ContractFactory {
    
      constructor(...args: MockCircuitVerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockCircuitVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockCircuitVerifier__factory {
      return super.connect(runner) as MockCircuitVerifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockCircuitVerifierInterface {
      return new Interface(_abi) as MockCircuitVerifierInterface;
    }
    
    override attach(address: string | Addressable): MockCircuitVerifier {
      return super.attach(address) as MockCircuitVerifier;
    }
  static connect(address: string, runner?: ContractRunner | null): MockCircuitVerifier {
      return new Contract(address, _abi, runner) as unknown as MockCircuitVerifier;
    }
  }

  
  